### PR TITLE
Added vpx img transpose routine

### PR DESCRIPTION
**Pull request by shawnpringle**
The commits solve issue 8; and include a small program for testing, an addition to the simple decoder example, and some routines in C++ for vpx.

### CODE REVIEW

**Comment by lu-zero** [comment]
It isn't what the issue is about. transpose is a set of functions already present in vpx that have to be converted to use VSX.

**Comment by shawnpringle** [comment]
That's not how the issue reads.  You are honour bound to close issue 8, and
pay the bounty.

Look assuming you are an honest person, write a signature for each routine
and explain what you really want in each of your bounties to reflect what
you really want.

Certainly I have learned a lot about libvpx internals and I would implement
for VSX, but if I did, would I get a similiar answer to what you have just
sent me?

**Comment by lu-zero** [comment]
I'm not even the one paying, I wanted to support VSX in libvpx to match at least the ARM variant and IBM put some bounties on my personal tree after =)

Your demands are quite wrongly targeted, had you asked before sending pull requests you'd had spared both of us time I guess.

**Comment by edelsohn** [comment]
Shawn,

I and IBM opened the issues and the bounties, not Luca.  If he and the VideoLAN community do not accept your patch as correct, it is not correct and you will not receive the bounty.  No one is "honor-bound" to pay you because of your demands. The bounty is paid when you satisfy the community, not your own, internal measure for success.  If you did not take the time to communicate with the VideoLAN community and ensure that you understood the issue and requirements for the patch, that is your fault. Berating Luca and the VideoLAN community is not helping you.

**Comment by shawnpringle** [comment]
Then you wont mind importing the pull request and marking issue 8 fixed. ^ ^

You assert that a transpose routine already exists.  What is its name and
in what file is it in?

**Comment by edelsohn** [comment]
Shawn, stop trolling. You will not receive the bounty for your initial patch. If you want to understand the true issue and solve the real problem, Luca may or may not accept a correct patch, but your abusive attitude is not a good way to introduce yourself to the community.

**Pull request closed without merging**
